name: Update README with EoC Notice

on:
  schedule:
    # ワシントン時間 8/13 20:00 → UTCでは 8/14 00:00
    - cron: "0 0 14 8 *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          EOC_TEXT=$(cat << 'EOF'

---

## Editorial Expression of Concern (EoC)

On 17 November 2021, *Science Advances* published the Research Article  
*"Discovery of anti-inflammatory physiological peptides that promote tissue repair by reinforcing epithelial barrier formation,"* by Oda et al.  

The authors informed the journal of an institutional investigation related to the experimental conditions used for Figure 2B.  
We are notifying readers while the institution reviews these issues.

The corresponding author has informed the journal that the paper is under institutional investigation.  
This repository contains R code that generates graphs using processed data provided by the first and corresponding author.  
It does **not** include the Figure 2B data referenced in the Erratum or EoC.  

However, because an EoC has been issued for the paper, **please refrain from using the data from this study**.
EOF
)
          # 末尾に追記（すでに同じテキストがある場合は追記しない）
          if ! grep -q "## Editorial Expression of Concern (EoC)" README.md; then
            echo "$EOC_TEXT" >> README.md
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Add EoC notice to README" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
